name: CID
description: "Welcome to CID - my first Flutter app! This is a fun project designed for 18+ audiences, showcasing my journey into app development."
publish_to: 'none'

version: 1.0.0+1  # Version 1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.6
  url_launcher: ^6.1.8
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  haptic_feedback: ^0.5.1+1

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Correct section name
flutter_icons:
  android: true
  ios: true
  image_path: "assets/photos/CID.jpg"
  min_sdk_android: 21 # android min sdk

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/photos/
    - assets/audios/

# Organization details
# This is typically specified in the AndroidManifest.xml and Info.plist files,
# but you can document it here for reference.
organization: com.yasir.ycs